hanami/guides

content/repositories/sql-queries.md

Document Repository query with raw SQL

---

content/introduction/getting-started.md

I did my best to improve the grammar in the guides. I intend to make another PR after this one to address what I consider style issues. 
Please let me know if any changes are necessary.

Getting Started grammar review

---

content/helpers/custom-helpers.md

Fix grammar, make the actions for each step more explicit, and fix a broken link.

Improve the explanation in Helpers: Custom Helpers

---

content/command-line/project.md

#11 has missed one occurrence of _Minitest_

Replace Minitest with RSpec

---

content/command-line/generators.md

I was missing an example that shows how to generate a nested action for nested resourceful routes. This PR adds an example in the generator guide.

Add example of generating nested actions

---

content/models/database-configuration.md

Add documentation how to use sequel plugins

---

content/actions/testing.md

Related to https://github.com/hanami/guides/issues/17

Add information about session in action tests

---

content/introduction/getting-started.md

Just a few things I found worth fixing.

Fix some wording

---

content/models/use-your-own-orm.md

Add example how to use rom4 with hanami

---

content/actions/control-flow.md
content/actions/overview.md
content/actions/share-code.md
content/actions/testing.md
content/architecture/overview.md
content/assets/content-delivery-network.md
content/associations/has-many-through.md
content/associations/has-one.md
content/helpers/html5.md
content/mailers/templates.md
content/projects/code-reloading.md
content/upgrade-notes/v090.md
content/upgrade-notes/v100.md
content/views/mime-types.md

These links were not Hugo friendly. Thanks for the great docs! 😄

Fix internal links

---

content/assets/compressors.md

https://github.com/hanami/assets/issues/78#issuecomment-331936905

Clarify limitations of builtin assets compressors

---

content/projects/logging.md

Address Typo in the documentation.

Address typo in  logging.md

---

README.md

New to hugo so I didn't know how to run the server :) Figured it can help others too.

Add development note (`hugo server -d`)

---

content/v1.3/introduction/getting-started.md

Fix URL of welcome page image

---

README.md
config.toml
netlify.toml

Document compatible hugo version

---

.gitignore
themes/hanami/layouts/_default/single.html

We were using `v0.49.2` in production.

Hugo `v0.104.3`

---

config.toml
themes/hanami/layouts/_default/single.html
themes/hanami/layouts/index.html

Please manual test with Netifly preview.
https://trello.com/c/93hWs3Rm

Ensure version switcher to land to Getting Started page

---

content/v2.0/application/settings.md

Tweak some grammar in settings guide.

---

content/v2.0/application/autoloading.md

Adds an initial guide to autoloading.

Add autoloading guide.

---

content/v2.0/application/code-reloading.md

Adds a short guide covering code reloading.

Add guide to code reloading.

---

content/v2.0/application/cli-commands.md
content/v2.0/application/environments.md

Adds the following (smaller) application guides:
- environments
- commands

Add smaller application guides.

---

content/v2.0/application/inflector.md

Adds a section the application guide on the inflector.

Add an inflector guide.

---

content/v2.0/architecture/slices.md

Add sections on standard app components, slice settings and slice loading.

Finish slices guide

---

content/v2.0/actions/overview.md
content/v2.0/actions/parameters.md

Resolves: https://trello.com/c/Cxry5P0K/302-actions-parameters
Extracted from: https://github.com/hanami/guides/pull/101

Guides 2.0 Actions # parameters

---

content/v2.0/actions/overview.md
content/v2.0/actions/request-and-response.md

Resolves: https://trello.com/c/nHBWjfbd/299-actions-request-and-response-objects
Extracted each of the sections of https://github.com/hanami/guides/pull/101 to the separate PR for easier merging process, and review.

Guides 2.0 - Actions# Request and Response objects

---

content/v2.0/application/config.md

[Preview](https://deploy-preview-138--hanami-guides.netlify.app/v2.0/application/config/)

Add app config guide

---

content/v2.0/introduction/getting-started.md

[✨ **Preview** ✨](https://deploy-preview-139--hanami-guides.netlify.app/v2.0/introduction/getting-started/)
Took a pass at lightly refreshing this and also signing off from the three of us.

Refresh the introductory note

---

content/v2.0/cli-commands/_index.md
content/v2.0/cli-commands/commands.md

Moves CLI commands to the top level.

Move CLI commands to top level.

---

content/v2.0/actions/inheritance.md

[✨ **Preview** ✨](https://deploy-preview-144--hanami-guides.netlify.app/v2.0/actions/inheritance/)

Add Actions: inheritance

---

content/v2.0/actions/http-caching.md
content/v2.0/actions/overview.md

Resolves: https://trello.com/c/6bovam7H/310-actions-http-caching

Add actions-http-caching

---

config.toml

Prepare for v2.0

---

themes/hanami/static/assets/css/theme.css

Set code font size to 0.9rem

---

themes/hanami/static/assets/css/theme.css

Resolves: https://trello.com/c/R73U4Nba/362-fix-code-block-font-size-it-is-too-big

Reduce font-size for code blocks

---

content/v2.0/app/container-and-components.md
content/v2.0/app/slices.md
content/v2.0/logger/usage.md

I stumbled across this minor things while updating my 2.0-alpha app.

Minor fixes

---

content/v2.0/actions/control-flow.md
content/v2.0/actions/request-and-response.md
content/v2.0/actions/status-codes.md

This relates to hanami/controller#413
cc @jodosha

Add documentation for symbolic status names

---

content/v2.0/actions/testing.md

I assumed you wanted a link. 🙂

Fix `rack-test` link format

---

content/v2.0/app/slices.md

Ref https://github.com/hanami/router/issues/251

Slice routes

---

content/v2.1/views/working-with-dependencies.md

Just a small section, but good to make this clear and use this as a lead-in to exposures.
Resolves #213.

Add “Views: working with dependencies”

---

content/v2.1/helpers/string-escaping.md
content/v2.1/views/templates-and-partials.md

Add "Views: templates and partials" section

---

content/v2.1/introduction/building-a-web-app.md

Found and removed some double spaces and a single typo.

Typos in building-a-web-app.md

---

content/v2.2/database/_index.md
content/v2.2/database/overview.md
content/v2.2/database/relations.md

Do we want to create a new 2.2 section in the menu, or should I be adding this to the 2.0 section?

First draft of 2.2 from Google Docs content

---

content/v2.2/introduction/building-a-web-app.md
content/v2.2/introduction/building-an-api.md

We have it set up out of the box now.

Remove DatabaseCleaner setup from guides

---

content/v2.2/introduction/getting-started.md

Hanami 2.2 requires Ruby 3.1 and newer.
https://rubygems.org/gems/hanami/versions/2.2.0

Update Ruby version requirement

---

content/v2.2/cli-commands/generate.md

Add component, migration, operation, relation, repo and struct commands.

Update available generator commands

---

content/v2.2/assets/overview.md

Fix small typo in overview.md

---

content/v2.2/app/autoloading.md

Discussion: https://discourse.hanamirb.org/t/app-wide-rack-middleware-and-lib/1123/6

Add section to clarify the lack of autoloading in the config dir

---

content/v2.2/database/configuration.md

Please check whether I understood things correctly. 😄 
Discussion: https://discourse.hanamirb.org/t/slices-dont-take-db-config-from-parent-by-default/1072

Clarify configure_ and import_from_parent configuration

---

content/v2.2/database/configuration.md

From https://github.com/hanami/hanami/issues/1505, I realized we were missing some of this info in the guides.

Improve database configuration guide

---

content/v2.2/introduction/building-a-web-app.md
content/v2.2/introduction/building-an-api.md

It seems that the `DB` namespace is missing. Ref #246.

Fix a repo class name

---

content/v2.2/introduction/building-a-web-app.md

The template files are under the `templates` directory in v2.2.

Fix a path of template file
