content/introduction/getting-started.md
I was following the getting started guide, and encountered this:
```sh
ttilberg@timdesktop:~/dev/hanami_hotdogs$ bundle exec rake test
rake aborted!
Don't know how to build task 'test' (see --tasks)
/home/ttilberg/.rbenv/versions/2.5.1/bin/bundle:23:in `load'
/home/ttilberg/.rbenv/versions/2.5.1/bin/bundle:23:in `<main>'
(See full trace by running task with --trace)
ttilberg@timdesktop:~/dev/hanami_hotdogs$ bundle exec rake --tasks
rake environment  # Load the full project
rake spec         # Run RSpec code examples
```
Hanami Version: v1.3.0
=> use `rake spec`; `rake test` doesn't exist.

content/introduction/getting-started.md
Gets the code examples closer to what the generators output. Removes unnecessary imports in specs and replaces class names with `described_class`.
=> Update code examples

content/actions/testing.md, content/command-line/project.md
RSpec is default since Hanami 1.3. This commit changes the places that
identified Minitest as default and replaced by RSpec
=> Change RSpec to default on guides

content/associations/has-many-through.md
The .new constructor call is unnecessary on the instantiated repo.
=> Fix code snippet: cannot instantiate repository instance

content/architecture/interactors.md
In the Getting Started Guide -> [Implementing Create Action ](https://github.com/hanami/guides/blame/master/content/introduction/getting-started.md#L787) section when `create_spec.rb` file is originally created, `let(:action)` is defined as  `described_class.new`. But when we proceed to Architecture -> Interactors guide, then we notice that `let(:action)` is set to the full name of the controller. This PR changes it to `described_class.new` so that it feels less confusing when you read Getting Started Guide and then Architecture -> Interactors guide and compare changes.
=> Use described_class in create book controller spec

content/helpers/forms.md
Fix a typo, fix the grammar, and make the phrasing more consistent
=> Clean up the introduction to Helpers: Forms

content/helpers/escape.md
“Whitelisted URLs” → “Whitelisted URL schemes”. It’s not for whitelisting individual URLs.
=> Helpers: Markup Escape – rename section header

content/architecture/interactors.md
When `params` are invalid, we don't expect to call the `AddBook` interactor. Since the controller is performing validation - the interactor is not used.
Change spec to match this, assert that interactor does not receive call.
=> Expect not to create a book if invalid

content/mailers/delivery.md
Adds information about `:logger` mode for mailer. This is very useful for development and I was quite upset it's not available. Then I wrote my own mode and then I discovered it was already available, but undocumented.
By the way, I think this should be default mode in development environment, so I'm thinking about adding it as default in `unstable` branch of `hanami/hanami` - WDYT?
=> Add information about :logger mailer mode

content/mailers/delivery.md, content/mailers/share-code.md, content/projects/code-reloading.md
* Add guides subdomain to broken links to fix https://github.com/hanami/hanami/issues/980
* Remove version 1.2 from urls
=> Fix broken 404 links to guides.hanamirb.org

themes/hanami/static/assets/css/theme.css
i hope this does not shoot through some global design styles, however, i do think it makes the site much more legible. colors are rather randomly darkened.
alternative: darken the font color for these elements.
see #9 
current:
changed:
=> improve readability of flash-like block elements

content/projects/rake.md
The original link was pointing to a page that no-longer exists
=> Fix broken link in rake.md

content/migrations/create-table.md
The previous link was pointing towards `models/postgresql/` which doesn't exist.
=> Fix link to dedicated article on PostgreSQL types

content/repositories/overview.md
I updated this to close #44, which has been left open for a few months.
=> Update link to point at ROM 5.0 docs

content/associations/has-many.md
Per Hanami/Model's issue #550, HasMany does not implement #one.
**Note:** This change is strongly related to https://github.com/hanami/model/pull/554. They should either be closed or merged together.
=> Remove #find_book from HasMany documentation

content/projects/logging.md
"information" has no plural form, so I fixed a bit of the surrounding grammar.
=> Fix grammar in sensitive information section

themes/hanami/static/assets/css/theme.css
Fix for https://github.com/hanami/guides/issues/62
=> Use purple color for links

content/introduction/getting-started.md
Small thing: the `add_book_spec.rb` can give a false positive because the link text to create a book is "New book" in `apps/web/templates/books/index.html.erb`, so even if the add failed and `books/index.html.erb` is rendered, this test would pass. I modified the title to differentiate it from the link text.
=> Change book title in `add_book_spec.rb`

content/assets/preprocessors.md
Hey, I've tried building a simple app with SCSS assets compilation, but when I added the `sass` gem as suggested in the docs it was crashing with following error:
it seems that the `sass` gem is deprecated and the authors suggest using `sassc`. After this change the assets started compiling normally.
=> Update Gemfile snippet in preprocessors.md

content/entities/custom-schema.md
The title says all.
I want to define entity attributes. It doesn't appear to be in the documentation.
So I added it.
=> Add entity definition to entity custom schema guide.

content/actions/testing.md
After reading the Hanami Guide from A to Z, I did not see any example describing how to assert values coming *from* the action. The only example showed how to pass values *into* the action.
Thanks to @kaikuchn for the [tip that unstuck me](https://gitter.im/hanami/chat?at=5f33bc5d79659c5fbfeb2021)!
=> Improve Session Testing with example of session OUT values

content/command-line/plugins.md
Not sure if it's something new (because of renaming `hanami-cli` to `dry-cli`?) - as I think it worked before. But now for freshly generated Hanami project (version 1.3.3) I needed to extend via `Hanami::CLI::Commands`.
=> Fix code sample for extending existing CLI commands

content/command-line/plugins.md
Fixed the invalid syntax and opted to just use a block vs a stabby lambda.
=> Fix Ruby syntax of plugin hook example

content/associations/has-many.md
The `has_many` guide specifies a `NOT NULL` constraint on the `author_id` foreign key, but this breaks the guide. I believe it's a mistake, judging by the migration used in the `hanami/model` [specs](https://github.com/hanami/model/blob/1fb18741c3c36a2db8d4269a385b99b7e9b16cf3/spec/support/fixtures/database_migrations/20160830094941_create_books.rb#L8).
At the bottom of the guide, `on_sale` is referenced as a column but wasn't created during the migration, which causes the examples to fail. The migration above has the `on_sale` column as an example, so it was copied over.
=> Update has_many guide to fix error

themes/hanami/layouts/index.html, themes/hanami/layouts/partials/footer.html
I don't know where / if the footer file is used, but these were the two places where `2018` appeared. 
I know that, for copyright purposes, `2018` is fine but I think it looks better to have the most recent year in the footer.
Happy to change it to `2018`-`{current year}`, if you prefer (or earlier even)
(If you're reading this and new to Go, like I am, [`2006` is a special formatting value that means `%Y` in strftime](https://golang.org/pkg/time/#pkg-constants))
=> Use 'now' for year, rather than hard-coded

content/v1.3/introduction/getting-started.md
We should tell users going through the Getting Started guide that Hanami v1.3 doesn't support Ruby 3.
See: 
- https://github.com/hanami/hanami/issues/1108
- https://github.com/hanami/hanami/issues/1101
I also created a PR to require Ruby 2 for Hanami v1.3: https://github.com/hanami/hanami/pull/1109
=> Add note about Hanami v1.3 requiring Ruby 2

themes/hanami/layouts/_default/single.html
By adding a `toggler` button and adjusting the navigation classes a little bit, I was able to fix the mobile navigation when browsing through documents.
**Before**
**After**
No visible changes in non-mobile devices (md, lg..)
**Before**
**After**
I suggest to review with: `?w=1` enabled: https://github.com/hanami/guides/pull/95/files?w=1
Resolves: #94
=> Bug/invisible sidebar on mobile 

config.toml
Hugo 0.60.0 switched Markdown engines, and now unsafe
rendering must be enabled manually.
https://gohugo.io/news/0.60.0-relnotes/
Fixes issues where raw HTML is excluded from rendering
Reported by @swilgosz
=> Enable unsafe markdown rendering

config.toml
One of the newer Hugo releases has increased security around the `getenv` function, and it prevents the callout to the `BRANCH` env variable on newer releases of Hugo, preventing builds.
=> Add `BRANCH` env variable to allowed getenv params

content/v1.3/architecture/interactors.md
Fix little error in the guide:
```ruby
def call
@book = BookRepository.new.create(book_attributes)
end
```
should be
```ruby
def call(book_attributes)
@book = BookRepository.new.create(book_attributes)
end
```
=> Fix minor typo

themes/hanami/static/assets/css/theme.css
There are some text spacing issues in the guides that I found distracting. `text-align: justify` seems to be the culprit. I'm not sure what the original intent for the style was, so this change may have consequences elsewhere that I'm not aware of.
**GIF**
=> Remove text-align: justify; from main p

content/v1.3/routing/overview.md
It looks like the `rack/rack` project changed the name of their default branch, and that the link needs the file's extension to be viewable.
The corrected link is available here:  https://deploy-preview-110--hanami-guides.netlify.app/v1.3/routing/overview/#rack
=> v1.3 - Fix a broken link

themes/hanami/layouts/_default/single.html, themes/hanami/static/assets/js/theme.js
Show in navigation bar a select to pick the versions of the documentation.
Once a reader changes the value of the select, they will be redirected to the requested version of the documentation.
The values of the select (the `<option>` tags) are automatically picked by the code, by looking at the `content/` directory. This is the directory where we'll have multiple versions of the documentation (e.g. `content/v1.3`, `content/v2.0`, etc..).
The page is rendered with selected `<option>`, according to the current section (e.g. v1.3)
---
=> Navigation version switch

content/v2.0/application/_index.md, content/v2.0/application/settings.md
This is adds a section on settings within an application guide.
Previewable [here](https://deploy-preview-122--hanami-guides.netlify.app/v2.0/application/settings/)
=> Add settings guide

content/v2.0/application/booting.md
This adds an initial guide to app booting, covering what a prepared and booted state means.
There may be more detail we can add here.
Ready for review!
=> Add initial application booting guide.

content/v2.0/actions/overview.md
This is covered in the parameters section now.
=> Remove parameters heading from action overview.

content/v2.0/logger/configuration.md, content/v2.0/logger/usage.md, themes/hanami/static/assets/css/theme.css
- Light gray background for inline code examples
- Less vibrant purple for header and buttons
- Same gray background for shell code blocks
- Reduce font size
- Make default font darker and use consistent 300 weight in both paragraphs and lists
This partly ports tweaks from #106 so see there for comparison screenshots.
=> Tweak CSS a bit

content/v2.0/actions/overview.md, content/v2.0/actions/testing.md
Resolves: https://trello.com/c/9GKXsM2x/311-actions-testing
=> Add actions-testing section

content/v2.0/introduction/getting-started.md
The change made:
What I'm seeing in my console when I follow the guides and run the test:
=> Add correct content type for examples

content/v2.0/app/slices.md
Slice providers must be under `slices/api/config/providers` instead under `slices/api/providers`.
Best regards
=> Fix slice-provider path

content/v2.0/app/settings.md, content/v2.0/app/slices.md, content/v2.0/cli-commands/commands.md, content/v2.0/introduction/getting-started.md, content/v2.0/routing/overview.md
Resolves: https://trello.com/c/QlZI0R5W/349-use-consistently-when-referring-to-shell-commands
=> Consistently use $ as a prefix for shell commands

content/v2.0/views/_index.md, content/v2.0/views/planned_for_2_1.md
In order to signpost a) when V1.3-style view support is coming to Hanami V2.x and to suggest what to do in the meantime, add a guides menu item for Views.
=> Add a v2.0 views placeholder

content/v2.0/actions/testing.md
Figured this is a typo, considering the rest of the document.
=> Fix actions testing path on example

content/v2.0/actions/request-and-response.md, content/v2.0/app/app-config.md, content/v2.0/app/providers.md
Resolves: https://trello.com/c/HOWUg5kK/359-check-for-and-fix-broken-links
Used: https://ahrefs.com/broken-link-checker
Went through each section URL, and pasted URL to check for broken links.
*Result:* No Links Broken (returning error responses). Unfortunately, it only checked external links (starting from domain).
Then I’ve listed all URLs manually.
All Links in our articles are listed in the text below.
```markdown
guides • content/v2.0/actions/control-flow.md:
211: See the [Routing guide](/v2.0/routing/overview/) for more information on named routes.
guides • content/v2.0/actions/cookies.md:
6: Actions can set [cookies](https://developer.mozilla.org/en-US/docs/Web/HTTP/Cookies) on outgoing requests via the `response` object.
guides • content/v2.0/actions/http-caching.md:
94: For more …
```
=> Fix broken links in all articles

themes/hanami/static/assets/css/theme.css
Reverts hanami/guides#163. This intersects poorly with #160, and makes all our code-formatted text way too tiny.
For example:
=> Revert "Reduce font-size for code blocks"

content/v2.0/actions/control-flow.md
example is calling `redirect_to` on `request) object where it should be `response`
=> fix redirect_to example

content/v2.0/app/slices.md
I noticed a minor typo on the slices settings page where the example code didn't have the `constructor` option key. 
This PR addresses that typo
=> correct the settings example for slice to contain a constructor key

content/v2.1/views/helpers.md
The goal here is to explain how helpers _fit_ within the larger view layer: both the standard helpers, and how users can write their own.
The job of documenting the actual helper methods themselves will be for other PRs populating the separate top-level _Helpers_ section.
Resolves #193
=> Guides 2.1: Add “Views: Helpers”

content/v2.1/helpers/_index.md, content/v2.1/helpers/overview.md, content/v2.1/helpers/string-escaping.md
Begin the "Helpers" section of the guides. Add an _Overview_ page and a _String escaping_ page.
The helpers overview page is kind of a stub, since it's only job really is to be a landing page that (a) can redirect the reader to the appropriate sub-section of the views guide to see how helpers _fit_ within views, or (b) encourage them to keep reading to learn more about specific helpers. Open to ideas about making this better, but I'm fine just to leave this as it is, too.
Add a first helper page while we're here: _String escaping_. This was called _Markup escaping_ in the 1.3 guides, but that felt a little awkward to me, so I've gone with the more general "String" term here. Happy to adjust based on feedback.
Resolves #198
Resolves #190
=> Add helpers section and string escaping guide

content/v2.1/helpers/numbers_helper.md
Added guides section for the NumbersFormatting Helper.
Resolves: #202
=> Guides v2.1: Numbers helpers documentation

content/v2.1/assets/overview.md
Minor typo I noticed when reading through the guides.
=> Fix typo in 'Assets CLI commands' section

content/v2.1/views/scopes.md
While talking about scopes, the guides mention parts, instead of scopes
=> Fix typo of using part instead of scope

content/v2.1/views/testing.md
Based on discussion https://discourse.hanamirb.org/t/testing-hanami-views/960/3
This PR should probably be merged after Sebastin's PR https://github.com/hanami/guides/pull/231 so that we could properly link this new page too
=> Add page about testing hanami-views

content/v2.2/introduction/building-a-web-app.md, content/v2.2/introduction/building-an-api.md
When executed in the development env, these commands will now operate on both the development _and_ test databases, saving us the extra work!
=> Remove separate db commands for test env

content/v2.2/cli-commands/assets.md, content/v2.2/cli-commands/commands.md, content/v2.2/cli-commands/db.md, content/v2.2/cli-commands/generate.md, content/v2.2/cli-commands/middleware.md, content/v2.2/cli-commands/routes.md, content/v2.2/cli-commands/version.md
For the CLI section, we'll need to have information about CLI commands for DB namespace.
Follow the same convention as with other CLI command docs.
=> [Guides] Add Hanami CLI documentation for DB commands

content/v2.2/introduction/building-a-web-app.md, content/v2.2/introduction/building-an-api.md, content/v2.2/introduction/getting-started.md
Call the initially created action `home.index` instead of `home.show`, since this matches better with people's expectations, from feedback.
Use `--skip-route` and `--skip-tests` options when generating actions to ensure we don't leave any errant routes or create soon-to-be-failing tests.
Other minor tweaks and fixes.
=> Update getting started guides for 2.2

config.toml
I don't think `copyright` is used anywhere but I'm not 100% sure so to be safe I updated the year instead of removing it.
=> Update hanamiversion to 2.2, and update copyright

content/v1.3/views/overview.md, content/v1.3/views/testing.md, content/v2.2/views/overview.md, content/v2.2/views/testing.md
I had a few links go to 1.3 instead of 2.2
The other pages in this folder are fine because they don't overlap with 2.x guides at all
=> Link to 2.2 instead of 1.3

content/v1.3/introduction/getting-started.md, content/v1.3/upgrade-notes/v060.md, content/v1.3/upgrade-notes/v070.md, content/v1.3/upgrade-notes/v080.md, content/v1.3/upgrade-notes/v090.md, content/v1.3/upgrade-notes/v100.md, content/v1.3/upgrade-notes/v110.md, content/v1.3/upgrade-notes/v120.md, content/v1.3/upgrade-notes/v130.md, themes/hanami/layouts/_default/single.html, themes/hanami/layouts/index.html, themes/hanami/layouts/partials/footer.html
We no longer use Gitter chat as a community contact point. Everything runs through [the forum](https://discourse.hanamirb.org/) instead. Drop all links to chat.
=> Link to forum instead of chat; drop snippets and social links

content/v2.2/introduction/building-a-web-app.md
This file is generated under `app/relations` in v2.2.
=> Fix a file path of `books.rb`

content/v2.2/routing/overview.md
As discussed in PR https://github.com/hanami/router/pull/282 , this  is an update of the guides to explain external redirects use cases
=> Update hanami guides with redirect cases

content/v2.2/actions/http-caching.md, content/v2.2/operations/overview.md
I think we can't use `params` without a receiver now.
=> Add missing receiver when using `params`

content/v2.1/assets/overview.md, content/v2.2/assets/overview.md
I was struggling with getting my dockerized Hanami app to serve static assets in production mode.
This PR might help other people on the same journey find the solution without going through the source code first.
=> Document HANAMI_SERVE_ASSETS env variable

static/robots.txt, themes/hanami/layouts/_default/single.html
Clean up for #302.
It's fine if the pages are around, IMO, but we don't want people to discover them. I also added a robots.txt to remove the already-indexed pages from search engines, which I'll be responsible for removing once we launch 2.3
=> Exclude v2.3 from dropdown
